data <- data.frame()
data <- read.csv("household_power_consumption.txt",sep = ";", na.strings = "?")
dataset <- subset(data,data$Date == "1/2/2007" | data$Date == "2/2/2007")
dataset <- na.omit(dataset)
dataset$timeall <- as.POSIXct(paste(dataset$Date,dataset$Time), format = "%d/%m/%Y %H:%M")
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(dataset$timeall, dataset$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
plot(dataset$timeall, dataset$Voltage, xlab = "datetime", ylab = "Voltage", type = "l")
plot(dataset$timeall, dataset$Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering")
lines(dataset$timeall, dataset$Sub_metering_2, col = "red")
lines(dataset$timeall, dataset$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), fill = c("black", "red", "blue"))
plot(dataset$timeall, dataset$Global_reactive_power, xlab = "datetime", ylab = "Global_reactive_power", type = "l")
dev.off()
